### ISSUE TITLE
project isn't running

### ISSUE THREAD

**Issue by matheusjardimb** [nicolaslopezj/simple-react-form-examples#2]
It seems a few dependencies are missing in the packages files.
Even after fixing those dependencies it is still not possible to add Authors (in order to create a post).

See error printed in the console:
`
modules.js?hash=bc80d73…:56629 Uncaught Error: There is no field "authors.0.0.name" in the schema.
    at getFieldComponent (modules.js?hash=bc80d73…:56629) ...
`

**Comment by AdamGerthel** [comment]
I'm also having trouble running this on Meteor. I downloaded the project as a zip and ran `meteor` but I'm getting:

```
I20171204-10:06:18.541(1)? [Error: Can't find npm module 'react/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
I20171204-10:06:18.593(1)? [Error: Can't find npm module 'react-addons-pure-render-mixin/package.json'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?]
```
